#!/bin/bash
# Usage conv file.name

# for in-game sprites
#TRANSPARENT_COLOR='#a56a6a'

# Font sprites
TRANSPARENT_COLOR='#ffffff'

while [ "$#" != "0" ]; do
	FILENAME=$1
	echo "Converting $FILENAME"
	convert $FILENAME -transparent $TRANSPARENT_COLOR $FILENAME
	shift
done


